version: '3.8'
services:
  prysmctl-generate-genesis:
    build:
      context: .
      dockerfile: prysmctl.Dockerfile
    container_name: prysmctl-generate-genesis
    volumes:
      - ./node1/data:/app/node1/data
      - ./node2/data:/app/node2/data
    command: ["/app/scripts/generate-genesis.sh"]

  node1:
    build: .
    container_name: node1
    volumes:
      - ./node1/data:/data
      - ./node1/nodekey:/app/nodekey
      - ./node1/beaconkey:/app/beaconkey
      - ./node1/config.toml:/app/config.toml
    environment:
      NODE_IDENTITY: "node-1"
      HTTP_PORT: 8545
      WS_PORT: 8546
      AUTHRPC_PORT: 8551
      METRICS_PORT: 6060
      P2P_PORT: 30303
      BEACON_RPC_PORT: 4000
      BEACON_GRPC_PORT: 3500
      BEACON_P2P_TCP_PORT: 13000
      BEACON_P2P_UDP_PORT: 12000
      BEACON_MONITORING_PORT: 8080
      VALIDATOR_RPC_PORT: 7000
      VALIDATOR_GRPC_PORT: 7500
      VALIDATOR_MONITORING_PORT: 8081
      VALIDATOR_START_INDEX: 0
      PEER_NODES: "/ip4/172.20.0.3/tcp/13001/p2p/16Uiu2HAmFz274W7rTgaeoifJwmtsRn9KVkvrvAmfNvg9gdhw89Gg /ip4/172.20.0.3/udp/12001/p2p/16Uiu2HAmFz274W7rTgaeoifJwmtsRn9KVkvrvAmfNvg9gdhw89Gg"
    ports:
      - "8545:8545"
      - "8546:8546"
      - "8551:8551"
      - "6060:6060"
      - "30303:30303"
      - "13000:13000"
      - "12000:12000/udp"
      - "4000:4000"
      - "3500:3500"
      - "7000:7000"
      - "7500:7500"
      - "8080:8080"
      - "8081:8081"
    networks:
      devnet:
        ipv4_address: 172.20.0.2
    depends_on:
      - prysmctl-generate-genesis

  node2:
    build: .
    container_name: node2
    volumes:
      - ./node2/data:/data
      - ./node2/nodekey:/app/nodekey
      - ./node2/beaconkey:/app/beaconkey
      - ./node2/config.toml:/app/config.toml
    environment:
      NODE_IDENTITY: "node-2"
      HTTP_PORT: 8547
      WS_PORT: 8548
      AUTHRPC_PORT: 8553
      METRICS_PORT: 6061
      P2P_PORT: 30304
      BEACON_RPC_PORT: 4001
      BEACON_GRPC_PORT: 3501
      BEACON_P2P_TCP_PORT: 13001
      BEACON_P2P_UDP_PORT: 12001
      BEACON_MONITORING_PORT: 8082
      VALIDATOR_RPC_PORT: 7001
      VALIDATOR_GRPC_PORT: 7501
      VALIDATOR_MONITORING_PORT: 8083
      VALIDATOR_START_INDEX: 1
      PEER_NODES: "/ip4/172.20.0.2/tcp/13000/p2p/16Uiu2HAmNYTUE5jNA1MidN53yaojJU22JKRnfDTRvudkeb7pUXTx /ip4/172.20.0.2/udp/12000/p2p/16Uiu2HAmNYTUE5jNA1MidN53yaojJU22JKRnfDTRvudkeb7pUXTx"
    ports:
      - "8547:8547"
      - "8548:8548"
      - "8553:8553"
      - "6061:6061"
      - "30304:30304"
      - "13001:13001"
      - "12001:12001/udp"
      - "4001:4001"
      - "3501:3501"
      - "7001:7001"
      - "7501:7501"
      - "8082:8082"
      - "8083:8083"
    networks:
      devnet:
        ipv4_address: 172.20.0.3
    depends_on:
      - prysmctl-generate-genesis

networks:
  devnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
