version: '3.8'
services:
  prysmctl-generate-genesis:
    build:
      context: .
      dockerfile: prysmctl.Dockerfile
    container_name: prysmctl-generate-genesis
    volumes:
      - ./scripts/:/app/scripts
      - ./node1/data:/app/node1/data
      - ./node2/data:/app/node2/data
    command: ["/app/scripts/generate-genesis.sh"]

  node1:
    build: .
    container_name: node1
    volumes:
      - ./node1/data:/data
      - ./node1/nodekey:/app/nodekey
      - ./node1/beaconkey:/app/beaconkey
      - ./node1/config.toml:/app/config.toml
    environment:
      NODE_IDENTITY: "node-1"
      VALIDATOR_START_INDEX: 0
      PEER_NODES: "/ip4/172.20.0.3/tcp/13001/p2p/16Uiu2HAmFz274W7rTgaeoifJwmtsRn9KVkvrvAmfNvg9gdhw89Gg /ip4/172.20.0.3/udp/12001/p2p/16Uiu2HAmFz274W7rTgaeoifJwmtsRn9KVkvrvAmfNvg9gdhw89Gg"
    ports:
      - "8545:8545"
      - "8546:8546"
      - "8551:8551"
      - "6060:6060"
      - "30303:30303"
      - "13000:13000"
      - "12000:12000/udp"
      - "4000:4000"
      - "3500:3500"
      - "7000:7000"
      - "7500:7500"
      - "8080:8080"
      - "8081:8081"
      - "3000:3000"
    networks:
      devnet:
        ipv4_address: 172.20.0.2
    depends_on:
      - prysmctl-generate-genesis

  node2:
    build: .
    container_name: node2
    volumes:
      - ./node2/data:/data
      - ./node2/nodekey:/app/nodekey
      - ./node2/beaconkey:/app/beaconkey
      - ./node2/config.toml:/app/config.toml
    environment:
      NODE_IDENTITY: "node-2"
      VALIDATOR_START_INDEX: 1
      PEER_NODES: "/ip4/172.20.0.2/tcp/13000/p2p/16Uiu2HAmNYTUE5jNA1MidN53yaojJU22JKRnfDTRvudkeb7pUXTx /ip4/172.20.0.2/udp/12000/p2p/16Uiu2HAmNYTUE5jNA1MidN53yaojJU22JKRnfDTRvudkeb7pUXTx"
    ports:
      - "8547:8545"
      - "8548:8546"
      - "8553:8551"
      - "6061:6060"
      - "30304:30303"
      - "13001:13000"
      - "12001:12000/udp"
      - "4001:4000"
      - "3501:3500"
      - "7001:7000"
      - "7501:7500"
      - "8082:8080"
      - "8083:8081"
      - "3001:3000"
    networks:
      devnet:
        ipv4_address: 172.20.0.3
    depends_on:
      - prysmctl-generate-genesis

networks:
  devnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
